services:
  nginx:
    container_name: entraid-nginx-1
    restart: unless-stopped
    build: ./nginx
    ports:
      - "82:80"
  fastapi:
    container_name: entraid-fastapi-1
    restart: unless-stopped
    build: ./fastapi
    ports:
      - "127.0.0.1:8001:8000"
    #environment:

networks:
  default:
    name: entraid-network